### ISSUE TITLE
run spilo without root group for postgres user

### ISSUE THREAD

**Issue by seekermarcel** [zalando/spilo#1010]
We want to run spilo as a non-root user. Preferably as the postgres user and group (101 and 103) so we don't have to migrate volumes.

However when we configure spilo to run in such a way, the postgres user is still part of the root group:
```bash
$ id
uid=101(postgres) gid=103(postgres) groups=103(postgres),0(root),102(ssl-cert)
```

We need an image where the postgres user is not part of the root group by default, or is this configurable in some other way?

Parts of the current config:
```yaml
    spilo_allow_privilege_escalation: false
    spilo_fsgroup: 103
    spilo_privileged: false
    spilo_runasgroup: 103
    spilo_runasuser: 101
```
