### ISSUE TITLE
Hi, maybe the document should be made clearer about how to use

### ISSUE THREAD

**Issue by seepine** [zalando/spilo#1021]
### Expect
Like postgres of hub.docker.com
```
docker run -d \
	--name some-postgres \
	-e POSTGRES_PASSWORD=mysecretpassword \
	-e PGDATA=/var/lib/postgresql/data/pgdata \
	-v /custom/mount:/var/lib/postgresql/data \
	postgres:16
```
Or docker swarm yml
```yml
version: '3.9'
services:
  db:
    image: postgres:16
    volumes:
      - /custom/mount:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    deploy:
      mode: replicated
      replicated: 5
```

### Now docs
![image](https://github.com/user-attachments/assets/0b92072d-bb51-4ea5-836e-239b3779c849)
