### ISSUE TITLE
failed to bootstrap from leader 'postgres-0'

### ISSUE THREAD

**Issue by RMrenex** [zalando/spilo#1116]
Hello,

I'm trying to install patroni in my k8s cluster, but it seems that my two replica pods can't synchronize with the master, and I don't understand why. They remain stuck on the step:

2025-05-05 07:09:52,808 INFO: Lock owner: postgres-0; I am postgres-1
2025-05-05 07:09:52,808 INFO: trying to bootstrap from leader 'postgres-0'
2025-05-05 07:09:52,809 ERROR: failed to bootstrap from leader 'postgres-0'

Here are my yaml configuration files :
patroni-statefulset.yaml

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: test-prod
spec:
  serviceName: postgres-headless
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 103

      serviceAccountName: patroni-sa
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              echo ">> Fixing ownership of PGROOT…"
              chown -R 101:103 /home/postgres/pgroot
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: pgdata
              mountPath: /home/postgres/pgroot

      containers:
        - name: patroni
          image: ghcr.io/zalando/spilo-17:4.0-p2
          imagePullPolicy: IfNotPresent
          ports:
            - name: restapi
              containerPort: 8008
            - name: postgresql
              containerPort: 5432

          env:
            - name: DCS_ENABLE_KUBERNETES_API
              value: "true"
            - name: KUBERNETES_USE_CONFIGMAPS
              value: "true"
            - name: KUBERNETES_ROLE_LABEL
              value: "spilo-role"
            - name: KUBERNETES_LEADER_LABEL_VALUE
              value: "master"
            - name: KUBERNETES_SCOPE_LABEL
              value: "version"
            - name: KUBERNETES_LABELS
              value: '{"application":"spilo"}'

            # ─── Identité du cluster ───
            - name: SCOPE
              value: "test"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: PGVERSION
              value: "17"
            - name: PGHOME
              value: "/home/postgres"
            - name: PGROOT
              value: "/home/postgres/pgroot"
            - name: PGDATA
              value: "/home/postgres/pgroot/pgdata"
            - name: APIPORT
              value: "8008"

            - name: PGUSER_SUPERUSER
              value: "postgres"
            - name: PGPASSWORD_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: patroni-db-credentials
                  key: postgres-superuser-password

            - name: PGUSER_ADMIN
              value: "admin"
            - name: PGPASSWORD_ADMIN
              valueFrom:
                secretKeyRef:
                  name: patroni-db-credentials
                  key: patroni-admin-password

            - name: PGUSER_STANDBY
              value: "replicator"
            - name: PGPASSWORD_STANDBY
              valueFrom:
                secretKeyRef:
                  name: patroni-db-credentials
                  key: replication-user-password

            - name: PGPORT
              value: "5432"

            - name: ENABLE_WAL_PATH_COMPAT
              value: "true"

          volumeMounts:
            - name: pgdata
              mountPath: /home/postgres/pgroot

  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: csi-cinder-high-speed
        resources:
          requests:
            storage: 10Gi
```

patroni-configmap.yaml

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
  namespace: test-prod
data:
  patroni.yml: |
    scope: test
    namespace: /service/
    name: {{ POD_NAME }}

    restapi:
      listen: 0.0.0.0:8008
      connect_address: {{ POD_IP }}:8008

    dcs:
      kubernetes:
        namespace: test-prod
        labels:
          app: postgres
        scope_label: scope
        role_label: role

    bootstrap:
      initdb:
        - encoding: UTF8
        - data-checksums

      users:
        admin:
          password: "{{ PATRONI_ADMIN_PASSWORD }}"
          options:
            - createrole
            - createdb
        replicator:
          password: "{{ PATRONI_REPLICATION_PASSWORD }}"
          options:
            - replication

    postgresql:
      listen: 0.0.0.0:5432
      connect_address: {{ POD_IP }}:5432
      data_dir: /home/postgres/pgroot/pgdata
      bin_dir: /usr/lib/postgresql/17/bin
      parameters:
        archive_mode: "off"
        wal_level: replica
        hot_standby: "on"
        synchronous_commit: "on"
        synchronous_standby_names: "*"

    watchdog:
      mode: off
```

Thank you for your help.
