### ISSUE TITLE
configure postgres using SPILO_CONFIGURATION

### ISSUE THREAD

**Issue by k1ng440** [zalando/spilo#337]
Hello,
I am trying to modify Postgres configuration using SPILO_CONFIGURATION with kubernetes DCS but they do not get to the postgres at all. I can see them in /home/postgres/postgres.yml

```
        - name: SPILO_CONFIGURATION
          value: | ## https://github.com/zalando/patroni#yaml-configuration
            bootstrap:
              dcs:
              postgresql:
                parameters:
                  max_connections: 100
                  autovacuum_max_workers: 5
                  effective_cache_size: 45297MB
                  default_statistics_target: 500
                  effective_io_concurrency: 200
                  maintenance_work_mem: 2GB
                  max_locks_per_transaction: 512
                  max_parallel_workers: 16
                  max_parallel_workers_per_gather: 8
                  max_replication_slots: 5
                  max_wal_senders: 5
                  max_wal_size: 8GB
                  max_worker_processes: 23
                  min_wal_size: 4GB
                  shared_buffers: 15099MB
                  tcp_keepalives_idle: 900
                  tcp_keepalives_interval: 100
                  timescaledb.max_background_workers: 4
                  work_mem: 48317kB
                  wal_keep_segments: 8
                  wal_buffers: 16MB

              initdb:
                - auth-host: md5
                - auth-local: trust
```

```
postgres@timescale-0:~$ cat postgres.yml
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      max_worker_processes: 23
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        autovacuum_analyze_scale_factor: 0.02
        autovacuum_max_workers: 5
        autovacuum_vacuum_scale_factor: 0.05
        checkpoint_completion_target: 0.9
        default_statistics_target: 500
        effective_cache_size: 45297MB
        effective_io_concurrency: 200
        hot_standby: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 500
        log_statement: ddl
        log_temp_files: 0
        maintenance_work_mem: 2GB
        max_connections: 100
        max_locks_per_transaction: 512
        max_parallel_workers: 16
        max_parallel_workers_per_gather: 8
        max_replication_slots: 5
        max_wal_senders: 5
        max_wal_size: 8GB
        max_worker_processes: 23
        min_wal_size: 4GB
        shared_buffers: 15099MB
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        timescaledb.max_background_workers: 4
        track_functions: all
        wal_buffers: 16MB
        wal_keep_segments: 8
        wal_level: hot_standby
        wal_log_hints: 'on'
        work_mem: 48317kB
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  - encoding: UTF8
  - locale: en_US.UTF-8
  - data-checksums
```
