### ISSUE TITLE
print logs to STDOUT

### ISSUE THREAD

**Issue by alice-sawatzky** [zalando/spilo#360]
right now spilo just fills up its storage with logs and dies, with the only workaround apparently being to distribute s3 credentials to all the spilo instances. many of us already have our own log aggregation systems that just gather the STDOUT/STDERR from running containers. Please provide an option to just print the logs rather than store them.

**Comment by Kampe** [comment]
I guess this is still a problem? Wow, uh? Things I didn't expect to encounter today.

**Comment by CyberDem0n** [comment]
I am sorry folks, we have neither time nor personal interest to implement such a feature.
Therefore in the spirit of open-source, anybody could start working on it, open a PR and we will review-merge it.

**Comment by alice-sawatzky** [comment]
fair enough! I'd volunteer, but my workplace has since moved to a different solution (running Patroni directly in kube) so I don't think I can justify the time contributing to a project we no longer use. it shouldn't be too hard for someone else to jump on this

**Comment by xzizka** [comment]
Hello,

We solved it by adding the following lines to the manifest
```
  postgresql:    
    version: "12"
    parameters:  # Expert section
      shared_buffers: "96MB"
      max_connections: "10"
      log_destination: "stderr"      <=add this line
      logging_collector: "false"     <=add this line
```
The all logs are send to stderr and not stored in the pod.
