### ISSUE TITLE
Could someone provide a docker-compose.yml example?

### ISSUE THREAD

**Issue by mths0x5f** [zalando/spilo#379]
I know this is a completely newbie question, but I'm using Docker Swarm to deploy things and I can't "speak" Kubernetes. 

For what I've found, I just need to use to setup HAProxy, etcd and spilo, right?

A docker-compose.yml more or less like the one supplied for Patroni testing is enough?

My apologies for such inconvenience but any help would be appreciated.

**Comment by mths0x5f** [comment]
I'm working on it, trying a lot of setups and figuring out some docs inconsistencies. I will add some notes while that.

* $PG_DATA and $PG_ROOT are not actually set to what is documented.

**Comment by mths0x5f** [comment]
```yaml
version: '3'
services:

  etcd1:
    image: bitnami/etcd:3.4.3
    command: etcd -name etcd1
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://10.0.0.11:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://10.0.0.11:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: pgEtcdCluster
    networks:
      network:
        ipv4_address: 10.0.0.11

  etcd2:
    image: bitnami/etcd:3.4.3
    command: etcd -name etcd2
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://10.0.0.12:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://10.0.0.12:2379
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: pgEtcdCluster
    networks:
      network:
        ipv4_address: 10.0.0.12

  postgres-node1:
    image: spilo:latest
    environment:
      ETCD_HOSTS: etcd1:2379,etcd2:2379
      PGPASSWORD_STANDBY: ${DB_PASS}
      PGPASSWORD_ADMIN: ${DB_PASS}
      PGPASSWORD_SUPERUSER: ${DB_PASS}
      SCOPE: pgCluster
    networks:
      network:
        ipv4_address: 10.0.0.21
    volumes:
      - db-data1:/home/postgres/pgdata

  postgres-node2:
    image: spilo:latest
    environment:
      ETCD_HOSTS: etcd1:2379,etcd2:2379
      PGPASSWORD_STANDBY: ${DB_PASS}
      PGPASSWORD_ADMIN: ${DB_PASS}
      PGPASSWORD_SUPERUSER: ${DB_PASS}
      SCOPE: pgCluster
    networks:
      network:
        ipv4_address: 10.0.0.22
    volumes:
      - db-data2:/home/postgres/pgdata

  haproxy:
    image: haproxy:2.0-alpine
    environment:
      MAX_CONN: 10000
      PG_NODE1_HOST: postgres-node1
      PG_NODE2_HOST: postgres-node2
    expose:
      - '2345'
    ports:
      - '2345:2345'
      - '7000:7000'
    networks:
      network:
    volumes:
      - ./conf/haproxy:/usr/local/etc/haproxy:ro

networks:
  network:
    ipam:
      config:
        - subnet: 10.0.0.1/24

volumes:
  db-data1:
  db-data2:
```

I came up with something like this, any comments about will be appreciated.

**Comment by sonix07** [comment]
@mths0x5f I do not work at zalando but I'm using this image with docker swarm. First of all this image already contains etcd so you do not need a separate one. 
```
version: "3.6"

services:

 tsnode1:
  image: spiloimage:notlatest
  networks:
   - db-nw
  ports: 
   - "5432:5432"
   - "8008:8008"
  volumes:
   - "/home/tstest/run1:/etc/service/etcd/run"
   - "/home/tstest/spilo1/pgdata:/home/postgres/pgdata/"
   - "/home/tstest/etcd1:/tmp"
  environment:
   - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
   - SCOPE=sftsscope
  deploy:
   replicas: 1

 tsnode2:
  image: spiloimage:notlatest
  networks:
   - db-nw
  ports: 
   - "5433:5432"
   - "8009:8008"
  volumes:
   - "/home/tstest/run2:/etc/service/etcd/run"
   - "/home/tstest/spilo2/pgdata:/home/postgres/pgdata/"
   - "/home/tstest/etcd2:/tmp"
  environment:
   - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
   - SCOPE=sftsscope
  deploy:
   replicas: 1

 tsnode3:
  image: spiloimage:notlatest
  networks:
   - db-nw
  ports: 
   - "5434:5432"
   - "8010:8008"
  volumes:
   - "/home/tstest/run3:/etc/service/etcd/run"
   - "/home/tstest/spilo3/pgdata:/home/postgres/pgdata/"
   - "/home/tstest/etcd3:/tmp"
  environment:
   - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
   - SCOPE=sftsscope
  deploy: 
   replicas: 1


networks:
  db-nw:
    driver: overlay
```
and for the ``run`` file I've mounted is to bootstrap the etcd cluster inside the spilo image.

run1: (needs to be marked as executable)
```
#!/bin/sh -e

exec 2>&1
exec env -i /bin/etcd --data-dir /tmp/etcd.data --name tsnode1 --initial-advertise-peer-urls http://tsnode1:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster tsnode1=http://tsnode1:2380,tsnode2=http://tsnode2:2380,tsnode3=http://tsnode3:2380,tsnode4=http://tsnode4:2380,tsnode5=http://tsnode5:2380 --initial-cluster-state new --initial-cluster-token etcd-cluster-1 --advertise-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001'
```
run2:
```
#!/bin/sh -e

exec 2>&1
exec env -i /bin/etcd --data-dir /tmp/etcd.data --name tsnode2 --initial-advertise-peer-urls http://tsnode2:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster tsnode1=http://tsnode1:2380,tsnode2=http://tsnode2:2380,tsnode3=http://tsnode3:2380,tsnode4=http://tsnode4:2380,tsnode5=http://tsnode5:2380 --initial-cluster-state new --initial-cluster-token etcd-cluster-1 --advertise-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001'
```
run3:

```
#!/bin/sh -e

exec 2>&1
exec env -i /bin/etcd --data-dir /tmp/etcd.data --name tsnode3 --initial-advertise-peer-urls http://tsnode3:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-cluster tsnode1=http://tsnode1:2380,tsnode2=http://tsnode2:2380,tsnode3=http://tsnode3:2380,tsnode4=http://tsnode4:2380,tsnode5=http://tsnode5:2380 --initial-cluster-state new --initial-cluster-token etcd-cluster-1 --advertise-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001'
```
