### ISSUE TITLE
Ability to configure timescaledb community (tsl) version

### ISSUE THREAD

**Issue by Thorsten-Totemic** [zalando/spilo#403]
Currently, the dockerfile builds the timescale extension with the `APACHE_ONLY=1` flag as set here: https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile#L169
Would it be possible to expose this as a configuration value so we could build the community (TSL license) Timescale version by using the Spilo image?

A little more background: We're using the [postgres-operator](https://github.com/zalando/postgres-operator) and we'd like to be able use the community version of timescaledb to benefit from the new compression feature.

**Comment by CyberDem0n** [comment]
If you wish, you and can introduce the new build arg for that and open a PR.
By default we will still build images with `APACHE_ONLY=1`.

**Comment by Thorsten-Totemic** [comment]
Thanks @CyberDem0n . I'll take a look at it.

**Comment by CyberDem0n** [comment]
Fixed in https://github.com/zalando/spilo/pull/419

**Comment by adamcharnock** [comment]
In case anyone is needing to create their own Spilo builds with `APACHE_ONLY=false`, this GitHub Actions workflow may help.

Placeholders are: `MY-REPO.EXAMPLE.COM`, `PROJECT_NAME`, `IMAGE_NAME`

```yaml
name: release

on:
  push:
    branches:
      - 'main'
  schedule:
    # Daily at midnight
    - cron:  '0 0 * * *'


jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/zalando/spilo/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Set environmental variable TAG_TO_BUILD"
        run: |
          echo "TAG_TO_BUILD=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}" >> $GITHUB_ENV

      - run: "echo latest release: ${{ env.TAG_TO_BUILD }}"

      - name: Get tags we have already built
        uses: fjogeleit/http-request-action@v1
        id: existing_tags
        with:
          url: 'https://MY-REPO.EXAMPLE.COM/v2/PROJECT_NAME/IMAGE_NAME/tags/list'
          method: 'GET'
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          ignoreStatusCodes: "404"

      - name: Checkout
        uses: actions/checkout@v2
        if: contains(steps.existing_tags.outputs.response, '"$TAG_TO_BUILD"')
        with:
          repository: 'zalando/spilo'
          ref: "${{ env.TAG_TO_BUILD }}"

      - name: Login to Harbor Container Registry
        uses: docker/login-action@v1
        if: contains(steps.existing_tags.outputs.response, '"$TAG_TO_BUILD"')
        with:
          registry: MY-REPO.EXAMPLE.COM
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        if: contains(steps.existing_tags.outputs.response, '"$TAG_TO_BUILD"')
        uses: docker/setup-buildx-action@v1

      - name: Build image
        if: contains(steps.existing_tags.outputs.response, '"$TAG_TO_BUILD"')
        uses: docker/build-push-action@v2
        with:
          context: postgres-appliance/
          file: postgres-appliance/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "MY-REPO.EXAMPLE.COM/PROJECT_NAME/IMAGE_NAME:${{ env.TAG_TO_BUILD }}"

          # THIS IS THE IMPORTANT BIT!
          build-args: |
            TIMESCALEDB_APACHE_ONLY=false
```
