### ISSUE TITLE
FATAL @src/pgqd.c:78 in function load_config(): failed to read config

### ISSUE THREAD

**Issue by sajjadG** [zalando/spilo#471]
Hi

I have a working spilo cluster setup and it's working fine but I have the following error on the master node (no matter which of my 3 node becomes master, it logs this FATAL error)
`FATAL @src/pgqd.c:78 in function load_config(): failed to read config`

```
version: '2.2'
services:
  spilo:
    image: registry.opensource.zalan.do/acid/spilo-12:1.6-p3
    network_mode: "host"
    environment:
      # https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst
      - SCOPE=pg-cluster
      - ETCD_HOSTS=host1:2379,host2:2379,host3:2379
      - PGPASSWORD_STANDBY=Passpass
      - PGPASSWORD_ADMIN=SecurePass
      - PGUSER_SUPERUSER=postgres
      - PGPASSWORD_SUPERUSER=mySecurePassw0rd
      - ALLOW_NOSSL=True
      - PGPORT=5432
      - PGVERSION=12
    volumes:
      - /pghome/:/home/postgres'

```
