### ISSUE TITLE
issue with clone from Azure blob storage via wal-g

### ISSUE THREAD

**Issue by kirillka415** [zalando/spilo#522]
Hi 
I  tested clone from Azure with wal-g  after  the pul request https://github.com/zalando/spilo/pull/514 was merged to master
and I  faced an issue 

when I apply yaml manifest using a "clone" section in the spec  to create new cluster from wal-g backup
and I got the following message:

`WARNING - Cloning with WAL-E is only possible when CLONE_WALE_*_PREFIX or CLONE_WALG_*_PREFIX or CLONE_WAL_*_BUCKET and CLONE_SCOPE are set.
`
But  I specified   CLONE_WALG_AZ_PREFIX and I have CLONE_SCOPE in a pod.

Here is my configMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  postgres-pod-config
  namespace: default
data:
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_SCHEDULE: "0 */12 * * *" 
  BACKUP_NUM_TO_RETAIN: "3" 
  WALG_AZ_PREFIX: "azure://datagrabber-backup/walg-folder/$(SCOPE)"
  AZURE_STORAGE_ACCOUNT: "<AZURE_STORAGE_ACCOUNT>"
  AZURE_STORAGE_ACCESS_KEY: "<AZURE_STORAGE_ACCESS_KEY>"
  WALG_DOWNLOAD_CONCURRENCY: "1"
  WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  WALG_DISABLE_S3_SSE: "true"    
  
  CLONE_WALG_AZ_PREFIX: "azure://datagrabber-backup/walg-folder/$(CLONE_SCOPE)"
  CLONE_AZURE_STORAGE_ACCOUNT: "<AZURE_STORAGE_ACCOUNT>"
  CLONE_AZURE_STORAGE_ACCESS_KEY: "<AZURE_STORAGE_ACCESS_KEY>"
  CLONE_WALG_DOWNLOAD_CONCURRENCY: "1"
  CLONE_WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  CLONE_USE_WALG_BACKUP: "true"
  CLONE_USE_WALG_RESTORE: "true"
  CLONE_WALG_DISABLE_S3_SSE: "true"
```

Here is  yaml manifest to clone cluster: 

```
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-pg-dbcluster-clon"
  namespace: "default"
  labels:
    team: acid
spec:
  clone:
    cluster: "acid-pg-dbcluster" # name of the original cluster
    uid: "14d60e8f-9623-4f69-86ad-abcd52109af2"
    timestamp: "2020-12-14T08:08:52.838+00:00"  
```

I found out if add 'AZ' by  modifying  "configure_spilo.py" it works fine 
before:
`name in ('S3', 'GS') and placeholders.get('{0}WALG_{1}_PREFIX'.format(prefix, name)) or\`
after:
`name in ('S3', 'GS', 'AZ') and placeholders.get('{0}WALG_{1}_PREFIX'.format(prefix, name)) or\`
Could you please have a look  ?

https://github.com/zalando/spilo/compare/master...kirillka415:fix_clone_from_azure
