### ISSUE TITLE
Simple backup and PITR configuration

### ISSUE THREAD

**Issue by lbartnicki92** [zalando/spilo#540]
Hi!
I'm currently trying to configure Zalando Operator with SPILO on Kubernetes Cluster.
I want to create such configuration, that will give me possibility to create pg_basebackup backup once a day(to local volume, not cloud), and if nessecery perform PITR from created backups.

I read all of Zalando Operator and SPILO documentation - there is no clear procedure for creating such backup and restore.
I had made some tests with BACKUP_SCHEDULE parameter, but no backup was created.

Could you tell me what SPILO variables I need to have set for making backups work?
And what SPILO parameters for PITR?

**Comment by CyberDem0n** [comment]
Spilo only supports backing up to the S3/GCS/Azure and similar that provided by wal-e/wal-g.
wal-g also supports backups to the local storage (WALG_FILE_PREFIX), therefore in theory Spilo could be extended to support it, but we don't plan to work on such a feature on our own.

In postgres-operator docs PITR and hidden under the clone section: https://github.com/zalando/postgres-operator/blob/a63ad49ef8101bb58725d892151279cd751df5c0/docs/user.md#clone-from-s3
But again, it supports only cloud services, not local volume

**Comment by xzizka** [comment]
Hello,

I also did some tests with backup configuration in different components of Postgres Operator.
When I placed the configuration into the Operator itself (using parameter logical_backup_schedule in the Postgres Operator config map) or directly in the manifest during the cluster creation (parameter logicalBackupSchedule) the _cron.job_ has been created.
![image](https://user-images.githubusercontent.com/9096952/111113764-289f2000-855a-11eb-8dec-890bc1906653.png)

 But when I tried to configure the same in the pod environment config map, no cron.job has been created. Just the PostgreSQL cluster. 

The configmap was configured in the Operator as an environment configmap.
![image](https://user-images.githubusercontent.com/9096952/111112786-ae21d080-8558-11eb-844c-5b08783b9210.png)
 
This is how the pod env config map looks like:
```
kubectl apply -f - <<EOF
apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: postgres-pod-config 
  namespace: postgres
data: 
  BACKUP_SCHEDULE: "40 * * * *" 
  USE_WALG_BACKUP: "true" 
  BACKUP_NUM_TO_RETAIN: "4" 
  AWS_ACCESS_KEY_ID: "************************"
  AWS_SECRET_ACCESS_KEY: "***************************"
  AWS_ENDPOINT: "https://s3.eu-central-1.wasabisys.com"
  AWS_REGION: "eu-central-1"
  WALG_DISABLE_S3_SSE: "false" 
  WAL_S3_BUCKET: "pg-dev"
EOF
```
What is the purpose of  BACKUP_SCHEDULE parameter in the pod environemnt config map?
I see the config parameter inside of the pod, but it looks like it does not take any effect.
![image](https://user-images.githubusercontent.com/9096952/111113426-add60500-8559-11eb-8538-d10e8412ad5d.png)

Thank you
