### ISSUE TITLE
ETCD_HOSTS not working (tags 2.0-p6)

### ISSUE THREAD

**Issue by fguiet** [zalando/spilo#575]
Hi,

This bug is present in tag : 2.0-p6 (last tag as of 2021/04/06)

I try to set up a docker-compose file to test multiple instance of spilo uqing an external etcd cluster.

So, I am using the environment variable `ETCD_HOSTS` like this:

`ETCD_HOSTS: etcd-node-1:2379,etcd-node-2:2381,etcd-node-3:2383`

See doc here : <https://github.com/zalando/spilo/blob/master/ENVIRONMENT.rst>

But I get the following error when launching the docker-compose :

```bash
spilo-node-2    | 2021-04-06 12:11:20,912 - bootstrapping - INFO - No meta-data available for this provider
spilo-node-2    | 2021-04-06 12:11:20,913 - bootstrapping - INFO - Looks like your running local
spilo-node-2    | Traceback (most recent call last):
spilo-node-2    |   File "/scripts/configure_spilo.py", line 1037, in <module>
spilo-node-2    |     main()
spilo-node-2    |   File "/scripts/configure_spilo.py", line 919, in main
spilo-node-2    |     config.update(get_dcs_config(config, placeholders))
spilo-node-2    |   File "/scripts/configure_spilo.py", line 649, in get_dcs_config
spilo-node-2    |     value = yaml.safe_load(value)
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
spilo-node-2    |     return load(stream, SafeLoader)
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
spilo-node-2    |     return loader.get_single_data()
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
spilo-node-2    |     node = self.get_single_node()
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/composer.py", line 35, in get_single_node
spilo-node-2    |     if not self.check_event(StreamEndEvent):
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
spilo-node-2    |     self.current_event = self.state()
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/parser.py", line 143, in parse_implicit_document_start
spilo-node-2    |     StreamEndToken):
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
spilo-node-2    |     self.fetch_more_tokens()
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 252, in fetch_more_tokens
spilo-node-2    |     return self.fetch_plain()
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 676, in fetch_plain
spilo-node-2    |     self.tokens.append(self.scan_plain())
spilo-node-2    |   File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 1299, in scan_plain
spilo-node-2    |     "Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.")
spilo-node-2    | yaml.scanner.ScannerError: while scanning a plain scalar
spilo-node-2    |   in "<unicode string>", line 1, column 2:
spilo-node-2    |     [etcd-node-1:2379,etcd-node-2:238 ...
spilo-node-2    |      ^
spilo-node-2    | found unexpected ':'
spilo-node-2    |   in "<unicode string>", line 1, column 13:
spilo-node-2    |     [etcd-node-1:2379,etcd-node-2:2381,etcd-node ...
spilo-node-2    |                 ^
spilo-node-2    | Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
````

A bit of my docker-compose.yml file

```yaml
 spilo-node-1:
    container_name: spilo-node-1
    image: spilo:2.0-p6
    depends_on:
      - etcd-node-1
      - etcd-node-2
      - etcd-node-3

    environment:
      # Spilo provider can be AWS, OpenStack, Google
      # See : https://github.com/zalando/spilo/blob/master/postgres-appliance/scripts/configure_spilo.py
      SPILO_PROVIDER: local
      ETCD_HOSTS: etcd-node-1:2379,etcd-node-2:2381,etcd-node-3:2383
      #ETCD_HOST: etcd-node-1:2379
      PGPASSWORD_STANDBY: brgm
      PGPASSWORD_ADMIN: brgm
      PGPASSWORD_SUPERUSER: brgm
      SCOPE: SPILO-CLUSTER

    volumes:
      - ./spilo-node-1/pgdata:/home/postgres/pgdata

    networks:
      - patroni_cluster_network

    restart: unless-stopped
```
