### ISSUE TITLE
Fails to start in OpenShift (SETUID cap required)

### ISSUE THREAD

**Issue by stepin** [zalando/spilo#605]
Please, answer some short questions which should help us to understand your problem / question better?

- **Which image of the operator are you using?**  registry.opensource.zalan.do/acid/postgres-operator:v1.6.3
- **Which image of the spilo are you using?**  registry.opensource.zalan.do/acid/spilo-13:2.0-p7
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** OKD (aka OpenShift) 4.7.9 / v1.20.0+7d0a2b2 on GCE
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

Spilo logs for non-default namespace:
```
2021-07-28 07:55:47,639 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2021-07-28 07:55:48,685 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
2021-07-28 07:55:48,686 - bootstrapping - INFO - No meta-data available for this provider
2021-07-28 07:55:48,686 - bootstrapping - INFO - Looks like your running local
2021-07-28 07:55:48,727 - bootstrapping - INFO - Configuring pam-oauth2
2021-07-28 07:55:48,728 - bootstrapping - INFO - Writing to file /etc/pam.d/postgresql
2021-07-28 07:55:48,728 - bootstrapping - INFO - Configuring pgqd
2021-07-28 07:55:48,729 - bootstrapping - INFO - Configuring pgbouncer
2021-07-28 07:55:48,729 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2021-07-28 07:55:48,729 - bootstrapping - INFO - Configuring bootstrap
2021-07-28 07:55:48,729 - bootstrapping - INFO - Configuring patroni
2021-07-28 07:55:48,742 - bootstrapping - INFO - Writing to file /run/postgres.yml
2021-07-28 07:55:48,743 - bootstrapping - INFO - Configuring log
2021-07-28 07:55:48,743 - bootstrapping - INFO - Configuring standby-cluster
2021-07-28 07:55:48,743 - bootstrapping - INFO - Configuring certificate
2021-07-28 07:55:48,743 - bootstrapping - INFO - Generating ssl certificate
2021-07-28 07:55:48,830 - bootstrapping - INFO - Configuring crontab
2021-07-28 07:55:48,830 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2021-07-28 07:55:48,831 - bootstrapping - INFO - Configuring wal-e
2021-07-28 07:55:50,271 INFO: Selected new K8s API server endpoint https://172.18.16.26:6443
2021-07-28 07:55:50,295 INFO: No PostgreSQL configuration items changed, nothing to reload.
2021-07-28 07:55:50,298 INFO: Lock owner: None; I am acid-minimal-cluster-1-0
2021-07-28 07:55:50,427 INFO: trying to bootstrap a new cluster
pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
2021-07-28 07:55:50,434 INFO: removing initialize key after failed attempt to bootstrap the cluster
2021-07-28 07:55:50,485 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2021-07-28-07-55-50
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 33, in <module>
    sys.exit(load_entry_point('patroni==2.0.2', 'console_scripts', 'patroni')())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 108, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 111, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1457, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1351, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1247, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1240, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
/run/service/patroni: finished with code=1 signal=0
```

Postgresql operator's resource:
```
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster-1
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "13"
```

It starts correctly in the default namespace but it don't start in non-default namespace.

Looks like according to error 'pg_ctl: cannot be run as root' image even should not try to start it under root.

**Comment by CyberDem0n** [comment]
I don't know how you are doing it.
By default uid for the postgres use is 101 (it is in the /etc/passwd):
```shell
$ id postgres
uid=101(postgres) gid=103(postgres) groups=103(postgres),0(root),102(ssl-cert)
```

Apparently, for some reason it becomes 0 in your case. Can it be that you /etc/passwd is weirdly mounted from outside?

P.S. since you are on OpenShift, the container is supposed to start with reduced privileges (non-root).

**Comment by stepin** [comment]
I don't change statefulset manually.

```
$ oc exec -it acid-minimal-cluster-1-0 -- bash
...
root@acid-minimal-cluster-1-0:/home/postgres# id postgres
uid=101(postgres) gid=103(postgres) groups=103(postgres),0(root),102(ssl-cert)

root@acid-minimal-cluster-1-0:/home/postgres# ps auxfw
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        1167  0.0  0.0  22044  4344 pts/0    Ss   13:36   0:00 bash
root        1185  0.0  0.0  37808  3368 pts/0    R+   13:37   0:00  \_ ps auxfw
root           1  0.0  0.0   4396   840 ?        Ss   07:55   0:00 /usr/bin/dumb-init -c --rewrite 1:0 -- /bin/sh /launch.sh
root           7  0.0  0.0   4640  1664 ?        S    07:55   0:00 /bin/sh /launch.sh
root          31  0.0  0.0   4564   780 ?        S    07:55   0:00  \_ /usr/bin/runsvdir -P /etc/service
root          32  0.0  0.0   4412   896 ?        Ss   07:55   0:00      \_ runsv pgqd
root          35  0.0  0.0  18384  3132 ?        S    07:55   0:00      |   \_ /bin/bash /scripts/patroni_wait.sh --role master -- /usr/bin/pgqd /home/
root        1166  0.0  0.0   4540   788 ?        S    13:36   0:00      |       \_ sleep 60
root          33  0.0  0.0   4412   800 ?        Ss   07:55   0:00      \_ runsv patroni
```

container definition:
```
  containers:
  - env:
    - name: SCOPE
      value: acid-minimal-cluster-1
    - name: PGROOT
      value: /home/postgres/pgdata/pgroot
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: PGUSER_SUPERUSER
      value: postgres
    - name: KUBERNETES_SCOPE_LABEL
      value: cluster-name
    - name: KUBERNETES_ROLE_LABEL
      value: spilo-role
    - name: PGPASSWORD_SUPERUSER
      valueFrom:
        secretKeyRef:
          key: password
          name: postgres.acid-minimal-cluster-1.credentials.postgresql.acid.zalan.do
    - name: PGUSER_STANDBY
      value: standby
    - name: PGPASSWORD_STANDBY
      valueFrom:
        secretKeyRef:
          key: password
          name: standby.acid-minimal-cluster-1.credentials.postgresql.acid.zalan.do
    - name: PAM_OAUTH2
      value: https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees
    - name: HUMAN_ROLE
      value: zalandos
    - name: PGVERSION
      value: "13"
    - name: KUBERNETES_LABELS
      value: '{"application":"spilo"}'
    - name: SPILO_CONFIGURATION
      value: '{"postgresql":{},"bootstrap":{"initdb":[{"auth-host":"md5"},{"auth-local":"trust"}],"users":{"zalandos":{"password":"","options":["CREATEDB","NOLOGIN"]}},"dcs":{}}}'
    - name: DCS_ENABLE_KUBERNETES_API
      value: "true"
    - name: KUBERNETES_USE_CONFIGMAPS
      value: "true"
    image: gcr.io/some-internal/acid/spilo-13:2.0-p7
    imagePullPolicy: IfNotPresent
    name: postgres
    ports:
    - containerPort: 8008
      protocol: TCP
    - containerPort: 5432
      protocol: TCP
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      readOnlyRootFilesystem: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/postgres/pgdata
      name: pgdata
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: postgres-pod-token-5bxm6
      readOnly: true
```

**Comment by stepin** [comment]
working pod in the default namespace don't have:
```
-      capabilities:
-        drop:
-        - KILL
-        - MKNOD
-        - SETGID
-        - SETUID
```

Statefulsets are the same. So, looks like it's some dynamic change of specific pod.

also, output from working pod:
```
root@acid-minimal-cluster-1-0:/home/postgres# ps auxfw
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        3209  0.2  0.0  22044  4344 pts/0    Ss   20:04   0:00 bash
root        3226  0.0  0.0  37808  3276 pts/0    R+   20:04   0:00  \_ ps auxfw
root           1  0.0  0.0   4396   760 ?        Ss   07:55   0:00 /usr/bin/dumb-init -c --rewrite 1:0 -- /bin/sh /launch.sh
root           7  0.0  0.0   4640  1716 ?        S    07:55   0:00 /bin/sh /launch.sh
root          31  0.0  0.0   4564   832 ?        S    07:55   0:00  \_ /usr/bin/runsvdir -P /etc/service
root          32  0.0  0.0   4412   772 ?        Ss   07:55   0:00      \_ runsv pgqd
postgres      34  0.0  0.0 108012  8096 ?        S    07:55   0:00      |   \_ /usr/bin/pgqd /home/postgres/pgq_ticker.ini
root          33  0.0  0.0   4412   856 ?        Ss   07:55   0:00      \_ runsv patroni
postgres      35  0.0  0.0 611500 37016 ?        Sl   07:55   0:29          \_ /usr/bin/python3 /usr/local/bin/patroni /home/postgres/postgres.yml
postgres      79  0.0  0.0 320528 30404 ?        S    07:55   0:02 /usr/lib/postgresql/13/bin/postgres -D /home/postgres/pgdata/pgroot/data --config-fi
postgres      81  0.0  0.0 200272  4456 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: logger
postgres      83  0.1  0.0 422528 23792 ?        Ssl  07:55   1:13  \_ postgres: acid-minimal-cluster-1: bg_mon
postgres      86  0.0  0.0 320660 17900 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: checkpointer
postgres      87  0.0  0.0 320668  6132 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: background writer
postgres      88  0.0  0.0 320528  8860 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: walwriter
postgres      89  0.0  0.0 321232  7240 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: autovacuum launcher
postgres      90  0.0  0.0 202392  4496 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: archiver last was 000000010000000000000001
postgres      91  0.0  0.0 202532  4496 ?        Ss   07:55   0:20  \_ postgres: acid-minimal-cluster-1: stats collector
postgres      92  0.0  0.0 322104 12500 ?        Ss   07:55   0:02  \_ postgres: acid-minimal-cluster-1: pg_cron launcher
postgres      93  0.0  0.0 321100  8332 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: TimescaleDB Background Worker Launcher
postgres      94  0.0  0.0 321092  7288 ?        Ss   07:55   0:00  \_ postgres: acid-minimal-cluster-1: logical replication launcher
postgres     100  0.0  0.0 324688 22440 ?        Ss   07:55   0:02  \_ postgres: acid-minimal-cluster-1: postgres postgres [local] idle
```

Looks like with dropped SETUID it can't change user from root to postgres.

Now it's interesting what part of the system drops that capabilities: openshift, operator, or spilo?

**Comment by CyberDem0n** [comment]
> working pod in the default namespace don't have:

>Looks like with dropped SETUID it can't change user from root to postgres.

> Now it's interesting what part of the system drops that capabilities from broken pod: openshift, operator, or spilo?

I can tell for sure that it is not Spilo, and most likely not Postgres-Operator either. 

Dropped capabilities would not be an issue if the container is started as non-root user and I am actually very surprised to see it running as root on OpenShift.

**Comment by stepin** [comment]
Yes, just found commands to fix it (maybe only 1 of 2 is required):
```
oc adm -n mydb policy add-scc-to-user anyuid -z postgres-pod
oc adm -n mydb policy add-scc-to-user privileged -z postgres-pod
```

or in a resource form:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:anyuid
  namespace: mydb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: postgres-pod
  namespace: mydb
```

In other words, spilo is not compatible with OpenShift by default: it starts with root user and then tries to change user. There were some change related to this (https://github.com/zalando/spilo/issues/428) but looks like it's not enough.

**Comment by stepin** [comment]
I will recheck other OpenShift settings. Most probably non-root user option is disabled but restricted policy is still enabled.

**Comment by CyberDem0n** [comment]
> In other words, spilo is not compatible with OpenShift by default: it starts with root user and then tries to change user.

We have good reasons to start it as root. For example, reducing priority with renice only works for root if privilege escalation is not allowed.

Besides that, OCP flawor of K8s isn't used widely, therefore it is not our top priority (we don't use it).

**Comment by stepin** [comment]
In my world (enterprises) OCP and Postgres are quite popular. Anyway, configuration is provided -- people will be able to find it. I think it can be more precise but it's work for future (like starting under postgres user with extra capabilities for renice).

**Comment by CyberDem0n** [comment]
We do have SYS_NICE capability, but unfortunately it doesn't work without root if privilege escalation is not allowed.

**Comment by stepin** [comment]
As I understand, if operator will add that capability like:
```
securityContext:
      capabilities:
        add:
        - SYS_NICE
```
 privilege escalation in the app is not needed. I didn't tested that, just my expectation from capabilities settings.
