### ISSUE TITLE
Possible problem when port is different by default (5432)

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#617]
Hi all,

I have a Kubernetes file to deploy Spilo. So far everything has worked properly. However, I need to change the port with a value different by default, for this reason I set:
```
PGPORT=5524
```

I deployed the cluster and everything is running. Running the command ```patronictl list``` everything is fine. However, in the Pod logs I see output like this:
```
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
2021-09-03 10:09:05,072 INFO: no action. I am (cfdb-ccdb-0) the leader with the lock
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
psql: error: could not connect to server: No such file or directory
```

There are still reference to 5432. Looking into the container I found that ```/home/postgres/postgres.yml``` has the following section:
```
kubernetes:
  bypass_api_service: true
  labels:
    application: cfdb-ccdb
  pod_ip: 192.168.140.18
  ports:
  - name: postgresql
    port: 5432
  role_label: role
  scope_label: dbinstance
  use_endpoints: true
```

Basically, it seems that the code that updates the leader still refers to the old port.
Is this a bug?
Should I specify the section above with the right port in the SPILO_CONFIGURATION variable?
