### ISSUE TITLE
spilo_kubernetes.yaml Configuration Consulting

### ISSUE THREAD

**Issue by Auggie321** [zalando/spilo#620]
To reduce the performance loss caused by postgres being installed inside a pod, 
how to deploy postgres master-slave, using a binary, on a local host. 
Only consider spilo,etcd,patroni installed inside the pod with statefulset;

 how to modify this file, please, thanks.
https://github.com/zalando/spilo/blob/master/kubernetes/spilo_kubernetes.yaml

**Comment by sasadangelo** [comment]
Hi,

First of all, consider that I am not a Spilo team member. I am working right now on Spilo because I am migrating a Patroni cluster from traditional infrastructure to Kubernetes.

Consider that Spilo=Patroni+PostgreSQL in a Pod
If you want an HA cluster you need to replicate in at least two Pods (I use three for example).
I don't think put everything in a single Pod improves much the performance. I did some performance tests a while ago and the bottleneck is always disks unless you totally load your DB in cache (Cache Hit Ratio=100%). So invest time and money in order good disks instead of waste your time in this such of improvements. Another thing to improve performance that gives good ROI is PostgreSQL and Kernel configuration.

In my project I started exactly from the same file, now I have a better code because I use Kustomize (included by default in kubectl) for templating, it is useful when you have a different environment where deploy (in my case Virtual Box for Unit Test and IBM Cloud for production and staging).

I suggest you proceed by steps:

1. the file above worked fine for IBM Cloud, no changes were required. For the Virtual box I needed to add:
```
  KUBERNETES_BYPASS_API_SERVICE: "false"
  KUBERNETES_SERVICE_HOST: "10.96.0.1"
```
don't ask me why for the first variable, I submit an issue and a Spilo team member suggested me to use it.

2. To run my cluster on Virtual Box there are several projects over there, I use my own cluster here:
https://github.com/sasadangelo/k8s-cluster/
it is very easy to set up, no strange stuff, it is based on Kubeadm.

3. For Etcd you need to add the following line to the above file:
```
ETCD_HOSTS: '"etcd-0.etcd:2379","etcd-1.etcd:2379","etcd-2.etcd:2379"'
```
and remove:
```
DCS_ENABLE_KUBERNETES_API: "true"
```
probably also the variables in 1 are useless if you use Etcd but I never tried to remove them.

4. Here is the file for Etcd I use:
```
---
apiVersion: v1
kind: Service
metadata:
  namespace: ibm-cfdb
  name: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd

---
apiVersion: v1
kind: Service
metadata:
  namespace: ibm-cfdb
  name: etcd-client
spec:
  type: NodePort
  ports:
    - name: etcd-client
      port: 2379
      protocol: TCP
      targetPort: 2379
      nodePort: 30080
  selector:
    app: etcd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ibm-cfdb
  name: etcd
  labels:
    app: etcd
spec:
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  replicas: 3
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:latest
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - name: data
              mountPath: /var/run/etcd
          command:
            - /bin/sh
            - -c
            - |
              PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
              exec etcd --name ${HOSTNAME} \
                --listen-peer-urls http://0.0.0.0:2380 \
                --listen-client-urls http://0.0.0.0:2379 \
                --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
                --initial-advertise-peer-urls http://${HOSTNAME}.etcd:2380 \
                --initial-cluster-token etcd-cluster-1 \
                --initial-cluster ${PEERS} \
                --initial-cluster-state new \
                --data-dir /var/run/etcd/default.etcd
      volumes:
        - name: data
          emptyDir: {}
```

Probably to make the Etcd database persistent you need to replace ```emptyDir: {}``` with a volumeClaimTemplates. However, for a first step ```emptyDir: {}``` is OK.

At this point, you should have a cluster working fine with Etcd. The next step should be start changing the configuration to match your need. The most important variable is SPILO_CONFIGURATION that will contain the postgres.yml Patroni configuration file. If you search the word "TEMPLATE" in Spilo code you'll find a default file Spilo use, SPILO_CONFIGURATION allows you to overwrite it. Don't spend time like me trying to change the default port (5432) or the data directory, it doesn't make sense for a container and Spilo doesn't have an easy way to do that. If you want a different port to configure it at the service level.

If you have a dev, staging, production env give a try to Kustomize as said above, I found it perfect to manage configuration for multiple environments. This is my experience so far, hope this helps you.
