### ISSUE TITLE
QUESTION: PostgreSQL users problem

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#621]
Hi,

I am migrating a Patroni solution in production on classical infrastructure to Kubernetes.
In our databases we have the following users:
* ```vcap```, it is a superuser and the DB administrator
* ```backup_user```, it is the replication user, it is a superuser (at the moment I ignore why it requires superuser privileges).

I am trying to replicate in Spilo this configuration and I used the following variables:
```
USE_ADMIN: "true"
PGUSER_ADMIN: "vcap"
PGUSER_SUPERUSER: "vcap"
PGUSER_STANDBY: "backup_user"
```

in a ConfigMap, the relative passwords in a secret, and then the following YAML for Spilo:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
spec:
  ...
  replicas: 3
  serviceName: cfdb-ccdb
  template:
    ...
    spec:
      ...
      containers:
      - name: cfdb-ccdb
        image: sasadangelo/spilo:11  # put the spilo image here
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: pgdata
          mountPath: /home/postgres/pgdata
        envFrom:
          - configMapRef:
              name: spilo-config
        env:
        ...
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: cfdb-ccdb
              key: superuser-password
        - name: PGPASSWORD_ADMIN
          valueFrom:
            secretKeyRef:
              name: cfdb-ccdb
              key: admin-password
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              name: cfdb-ccdb
              key: replication-password
          ...
```

The problem is that it's not clear to me the variables above how they are supposed to work. It seems that Spilo requires the presence of the ```postgres``` user, in fact from log on one Pod I see the following:
```
The files belonging to this database system will be owned by user "postgres".
...
GRANT
CREATE EXTENSION
DO
CREATE TABLE
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ERROR:  role "postgres" does not exist
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ERROR:  role "postgres" does not exist
GRANT
CREATE FOREIGN TABLE
GRANT
CREATE VIEW
ERROR:  role "postgres" does not exist
GRANT
...
2021-09-06 15:37:01.694 34 ERROR connection error: PQconnectPoll
2021-09-06 15:37:01.694 34 ERROR 
```

What I should do if I want vcap as DB administrator and backup_user as standby? Does Spilo always require that a ```postgres``` user exists? Is it possible declare vcap and backup_user as superuser in some way?
