### ISSUE TITLE
QUESTION: Etcd SSL support in Patroni

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#630]
Hi,

I need to add Etcd SSL in ```postgres.yml``` and I noticed documentation report these variables:
* ETCD_CACERT
* ETCD_CERT
* ETCD_KEY

I used them in a test and I noticed that the file is expanded directly into the file. A bit ugly from my point of view. Now one approach could be another PR similar to the one for PostgreSQL and REST API.

Where the variables above are used in the code?
```
grep -rin ETCD_CACERT *
ENVIRONMENT.rst:9:- **ETCD_CACERT**: Etcd CA certificate. If present it will enable validation.
```

I only see them in ENVIRONMENT.rst file and I am sure Spilo uses them because I have evidence from tests. I checked also Patroni code but no luck. Can someone help me to figure out this thing?

**Comment by CyberDem0n** [comment]
> Where the variables above are used in the code?

It is a bit "obfuscated": https://github.com/zalando/spilo/blob/3931f8e5a451567fec42c539afa8926798dd6573/postgres-appliance/scripts/configure_spilo.py#L657-L676

**Comment by sasadangelo** [comment]
Ok, thank you.
This time for Etcd I used a different approach. Let me first say that I wasn't aware it would be possible to mount certificates directly from the secret files. Reasoning on an Alexander comment on my PR and talking with a colleague we figure out this.
I have three certificates for Etcd server and three for Peers. Then in Etcd YAML file I added this code:
```
      - name: etcd-certificates
        secret:
          secretName: cfdb-ccdb
          items:
          - key: etcd-ca-cert
            path: etcd.ca_cert
            mode: 0644
          - key: etcd-private-key
            path: etcd.private_key
            mode: 0600
          - key: etcd-public-cert
            path: etcd.public_cert
            mode: 0644
          - key: etcd-peer-ca-cert
            path: etcd-peer.ca_cert
            mode: 0644
          - key: etcd-peer-private-key
            path: etcd-peer.private_key
            mode: 0600
          - key: etcd-peer-public-cert
            path: etcd-peer.public_cert
            mode: 0644
...
          volumeMounts:
            - name: etcd-certificates
              mountPath: /var/run/etcd-certs
```

On Patroni I only needed to mount the Etcd server certificates with something like this:
```
      volumes:
      - name: certificates
        secret:
          secretName: cfdb-ccdb
          items:
          - key: etcd-ca-cert
            path: etcd.ca_cert
            mode: 0644
          - key: etcd-private-key
            path: etcd.private_key
            mode: 0600
          - key: etcd-public-cert
            path: etcd.public_cert
            mode: 0644

        volumeMounts:
        - name: certificates
          mountPath: /home/postgres/pgdata/tmp-certs
```

the problem in Patroni is that certificates are owned by root and not postgres. There is no feature in Kubernetes that allow you to change the owner. The only way to change the owner ware to use an init container, mount them in a temp folder and then copy on PV and change the owner to postgres. The init container has a script to copy and change the owner.

@CyberDem0n  hope this solution make sense and I was wondering if there is a better way to have private key owned by postgres without the use of the init container.
