### ISSUE TITLE
Problem with CALLBACK_SCRIPT variable

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#637]
There is a problem I have a hard time figuring out. Looking at the ```TEMPLATE``` code in ```configure_spilo.py``` I see this:

```
callbacks:
  {{#CALLBACK_SCRIPT}}
    on_start: {{CALLBACK_SCRIPT}}
    on_stop: {{CALLBACK_SCRIPT}}
    on_role_change: '/scripts/on_role_change.sh {{HUMAN_ROLE}} {{CALLBACK_SCRIPT}}'
 {{/CALLBACK_SCRIPT}}
 {{^CALLBACK_SCRIPT}}
    on_role_change: '/scripts/on_role_change.sh {{HUMAN_ROLE}} true'
 {{/CALLBACK_SCRIPT}}
```

So I expect that if I don't define ```CALLBACK_SCRIPT``` I should expect the following in ```postgres.yml```:
```
  callbacks:
    on_role_change: /scripts/on_role_change.sh ....
```

instead, I got this:
```
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos python3 /scripts/callback_role.py
    on_start: python3 /scripts/callback_role.py
    on_stop: python3 /scripts/callback_role.py
```

the strange thing is that a few days ago I started to play with the variable CALLBACK_SCRIPT and before this everything was fine. Then I played a bit with it but after few hours I removed it totally from my code:
```
salvatores-MBP:patroni-kubernetes sasadangelo$ grep -rin CALLBACK_SCRIPT *
salvatores-MBP:patroni-kubernetes sasadangelo$ 
```

but the behavior explains above occurs. How is this possible?

PS
I don't have the ```callbacks``` section in SPILO_CONFIGURATION.
