### ISSUE TITLE
Bootstrap from Backup with PgBackrest

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#642]
Hi @CyberDem0n and team,

In the context of my activities to add the PgBackrest support to Spilo:
https://github.com/zalando/spilo/issues/638

I am trying to bootstrap my cluster from a backup previously done. Here is what I have done:
1. Startup a fresh cluster
2. Add a custom database 'mydb' just to verify after restore that it restored everything correctly.
3. Manual backup with PgBackrest on my S3 repo.
4. Scratch everything
5. Start a cluster with bootstrap from backup configured. Basically, I added these lines to the postgres.yml:
```
      method: clone_with_pgbackrest
      clone_with_pgbackrest:
        command: pgbackrest --stanza=ccdb --config-path /run/etc --log-level-console=info --delta restore
        keep_existing_recovery_conf: True
        no_params: True
        recovery_conf:
          recovery_target_timeline: latest
          recovery_target_action: promote
          restore_command: pgbackrest --stanza=ccdb --config-path /run/etc archive-get %f %p
```

My problem is that the backup is correctly restored in the data directory, but Patroni has issues connecting to PostgreSQL.
```
2021-09-30 07:48:16,156 INFO: Error communicating with PostgreSQL. Will try it again later
```

The problem in PostgreSQL is the following:
```
[unknown] postgres postgres ::1(43784) 2021-09-30 07:49:20.699 UTCFATAL:  no pg_
hba.conf entry for host "::1", user "postgres", database "postgres", SSL off
```

The problem is that my ```pg_hba.conf``` is not the one I had when I performed the backup, but I see this:
```
# Do not edit this file manually!
# It will be overwritten by Patroni!
local   replication     backup_user             trust
local   all     postgres                trust
```

I tried to put in my ```SPILO_CONFIGURATION``` my ```pg_hba``` in the ```bootstrap``` section like this:
```
bootstrap:
      ...
      pg_hba:
        - local   all         postgres                     trust
        - local   all         vcap                         trust
        - local   replication backup_user                  trust # Required on slaves where patroni connect to PostgreSQL with replication user
        - host    all         postgres        127.0.0.1/32 trust
        - host    all         vcap            127.0.0.1/32 trust
        - host    all         postgres        ::1/128      trust
        - host    all         vcap            ::1/128      trust
        - hostssl replication backup_user     0.0.0.0/0    md5
        - hostssl all         all             0.0.0.0/0    md5
```

and I correctly see it in the deployed ```postgres.yml``` but the ```pg_hba.conf``` is the incorrect one shown above.
What I am missing?
