### ISSUE TITLE
How to use as a service in GitHub actions?

### ISSUE THREAD

**Issue by bchrobot** [zalando/spilo#681]
Our production stack runs on Spilo via `postgres-operator`. We use GitHub Actions for our CI/CD and are trying to use Spilo as a workflow service to run tests against to mirror production as closely as possible.

```yaml
name: CI/CD Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.13.1-buster

    container:
      image: node:${{ matrix.node-version }}

    services:
      postgres:
        image: registry.opensource.zalan.do/acid/spilo-13:2.1-p3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: zalando
          ALLOW_NOSSL: 'true'
        options: >-
          --health-cmd "pg_isready -h localhost -p 5432"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

These are the same health options we have used successfully with `postgres` and `timescale/timescaledb` images.

`pg_isready` is exiting with a non-zero exit code and we cannot figure out why. It seems we do not have access to the service container's logs in GH Actions making debugging more difficult.

The logs we do have are:

```
Waiting for all services to be ready
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9fcdb869ab5cc3be93a7eb29ce98d0cd33189422855f6d12ac2d23b2a3e1e5bf
  starting
  postgres service is starting, waiting 2 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9fcdb869ab5cc3be93a7eb29ce98d0cd33189422855f6d12ac2d23b2a3e1e5bf
  starting
  postgres service is starting, waiting 3 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9fcdb869ab5cc3be93a7eb29ce98d0cd33189422855f6d12ac2d23b2a3e1e5bf
  starting
  postgres service is starting, waiting 7 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9fcdb869ab5cc3be93a7eb29ce98d0cd33189422855f6d12ac2d23b2a3e1e5bf
  starting
  postgres service is starting, waiting 17 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9fcdb869ab5cc3be93a7eb29ce98d0cd33189422855f6d12ac2d23b2a3e1e5bf
  starting
  postgres service is starting, waiting 32 seconds before checking again.
  /usr/bin/docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" 9fcdb869ab5cc3be93a7eb29ce98d0cd33189422855f6d12ac2d23b2a3e1e5bf
  unhealthy
  Error: Failed to initialize, postgres service is unhealthy.
```

Does anyone have experience using the `spilo` image as a GH Action service?

Any ideas on what else we might try to get the health check working?

Thank you!

**Comment by CyberDem0n** [comment]
I don't have much experience with GH Actions services, but:
1. `--health-cmd ` could be just `pg_isready`. This way it will connect via unix socket to a standard port.
2. There are no `POSTGRES_DB`, `POSTGRES_USER`,  and `POSTGRES_PASSWORD` env variables in spilo. The `postgres` is already a default DB. Instead of the last two, there are `PGUSER_SUPERUSER` and `PGPASSWORD_SUPERUSER` with default values `postgres` and `zalando` respectively.

**Comment by bchrobot** [comment]
Thanks @CyberDem0n !

We tried with just `pg_isready` and playing around with different envvar combinations but still no luck.

Running the image locally with the same health check works fine:

```sh
export CONTAINER_ID=$(
  docker run -d \
    --health-cmd "pg_isready" \
    --health-interval 10s \
    --health-timeout 5s \
    --health-retries 5 \
    registry.opensource.zalan.do/acid/spilo-14:2.1-p3
)

docker inspect  --format="{{json .State.Health}}" $CONTAINER_ID | jq
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2022-01-06T02:52:22.448835969Z",
      "End": "2022-01-06T02:52:22.577878115Z",
      "ExitCode": 2,
      "Output": "/var/run/postgresql:5432 - no response\n"
    },
    {
      "Start": "2022-01-06T02:52:32.589563925Z",
      "End": "2022-01-06T02:52:32.697595065Z",
      "ExitCode": 0,
      "Output": "/var/run/postgresql:5432 - accepting connections\n"
    },
    {
      "Start": "2022-01-06T02:52:42.706218785Z",
      "End": "2022-01-06T02:52:42.89027612Z",
      "ExitCode": 0,
      "Output": "/var/run/postgresql:5432 - accepting connections\n"
    }
  ]
}
```

so it does appear to be GitHub Actions specific 😔

**Comment by bchrobot** [comment]
We are working around the problem for now using:

```yaml
    services:
      postgres:
        image: registry.opensource.zalan.do/acid/spilo-14:2.1-p3
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

**Comment by bchrobot** [comment]
For anyone finding their way here from Google, we eventually figured out that the issue was unspecified DCS.

A working configuration with `SPILO_PROVIDER` set:

```yaml
    services:
      postgres:
        image: registry.opensource.zalan.do/acid/spilo-14:2.1-p6
        env:
          ALLOW_NOSSL: 'true'
          PGVERSION: '14'
          SPILO_PROVIDER: local
          PGUSER_SUPERUSER: postgres
          PGPASSWORD_SUPERUSER: zalando
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```
