### ISSUE TITLE
Restore with wal_e doesn't work

### ISSUE THREAD

**Issue by CyberDem0n** [zalando/spilo#72]
Missing:
```yaml
postgresql:
  create_replica_method:
  - wal_e
  - basebackup
```

So it always defaults to `basebackup` method
