### ISSUE TITLE
readiness probe failure  when using /readiness 

### ISSUE THREAD

**Issue by devulm** [zalando/spilo#892]
hi .

We are using image spilo-12:1.6-p3 on openshift 4.11 , via the postgres operator

The readiness does not work when path is set to /readiness . But works when updating it /patroni

let me know if i need to share the operatorconfiguration CRD.

```

        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

```

Below config works.
```
   - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /patroni
            port: 8008
            scheme: HTTP
          initialDelaySeconds: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

```
