### ISSUE TITLE
./run: 21: ulimit: error setting limit (Operation not permitted)

### ISSUE THREAD

**Issue by Richard87** [zalando/spilo#895]
The pod is trying to execute `set ulimit`, but is not allowed to, is this a bug?

Should ulimit be called, and if so, should the pod be configured to have the capability?

Clone of this closed issue: https://github.com/zalando/spilo/issues/881

I added this to the helm chart, but it had no effect:
```yaml
securityContext:
  capabilities:
    add:
    - CAP_SYS_RESOURCE
```

To fix it I had to manually edit the statefulset and delete the db-pod...

But, Will this be reset when the operator reconcile the statefulset in the future?
