### ISSUE TITLE
json log option

### ISSUE THREAD

**Issue by morgoved** [zalando/spilo#972]
Hello i use this configuration 

```
        - name: SPILO_CONFIGURATION
          value: | ## https://github.com/zalando/patroni#yaml-configuration
            postgresql:
              parameters:
                log_destination: jsonlog
                logging_collector: on
            bootstrap:
              postgresql:
                parameters:
                  log_destination: jsonlog
                  logging_collector: off
              initdb:
                - auth-host: md5
                - auth-local: trust
```

but i see into output 

```
2024-02-18 11:03:24.463 UTC [2857] LOG:  invalid value for parameter "log_destination": "jsonlog"
2024-02-18 11:03:24.463 UTC [2857] DETAIL:  Unrecognized key word: "jsonlog".
```

i use 15 postgres version - it's should works but i don't why it's not working
